platform :ios, '7.0'

pod 'AFNetworking'
pod 'Reachability'
#pod 'EZAudio', '~> 0.0.3'
pod 'CocoaLumberjack'
pod 'GoogleAnalytics-iOS-SDK'
pod 'BaseModel'
pod 'Selene'
pod 'TransitionKit', '~> 2.0.0'
pod 'Base64Encoder', :git => 'https://github.com/chenyongwei/Base64Encoder-iOS.git'